name: fastai
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_1003
  - attrs=18.2.0=py_0
  - backcall=0.1.0=py_0
  - beautifulsoup4=4.7.1=py36_1001
  - bleach=3.1.0=py_0
  - bottleneck=1.2.1=py36h3010b51_1001
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - cffi=1.11.5=py36h9745a5d_1001
  - chardet=3.0.4=py36_1003
  - cryptography=2.3.1=py36hb7f436b_1000
  - cycler=0.10.0=py_1
  - cytoolz=0.9.0.1=py36h14c3975_1001
  - dbus=1.13.0=h4e0c4b3_1000
  - decorator=4.3.0=py_0
  - dill=0.2.8.2=py36_1000
  - entrypoints=0.3=py36_1000
  - expat=2.2.5=hf484d3e_1002
  - fontconfig=2.13.1=h2176d3f_1000
  - freetype=2.9.1=h94bbf69_1005
  - gettext=0.19.8.1=h9745a5d_1001
  - glib=2.56.2=had28632_1001
  - gmp=6.1.2=hf484d3e_1000
  - gst-plugins-base=1.12.5=h3865690_1000
  - gstreamer=1.12.5=h0cc0488_1000
  - icu=58.2=hf484d3e_1000
  - idna=2.8=py36_1000
  - ipykernel=5.1.0=py36h24bf2e0_1001
  - ipython=7.2.0=py36h24bf2e0_1000
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.2=py36_1000
  - jinja2=2.10=py_1
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.0.0a3=py36_1000
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.4=py_0
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.0.1=py36h6bb024c_1002
  - libffi=3.2.1=hf484d3e_1005
  - libgcc-ng=7.3.0=hdf63c60_0
  - libgfortran-ng=7.2.0=hdf63c60_3
  - libiconv=1.15=h14c3975_1004
  - libpng=1.6.36=h84994c4_1000
  - libsodium=1.0.16=h14c3975_1001
  - libstdcxx-ng=7.3.0=hdf63c60_0
  - libtiff=4.0.10=h9022e91_1002
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.8=h143f9aa_1005
  - markupsafe=1.1.0=py36h14c3975_1000
  - matplotlib=3.0.2=py36h8a2030e_1001
  - matplotlib-base=3.0.2=py36h167e16e_1001
  - mistune=0.8.4=py36h14c3975_1000
  - mkl_fft=1.0.10=py36h14c3975_1
  - mkl_random=1.0.2=py36h637b7d7_2
  - msgpack-numpy=0.4.3.2=py_0
  - msgpack-python=0.6.0=py36h6bb024c_1000
  - murmurhash=1.0.0=py36hfc679d8_0
  - nb_conda=2.2.1=py36_0
  - nb_conda_kernels=2.2.0=py36_1000
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.8.2=h6bb024c_1001
  - notebook=5.7.4=py36_1000
  - numexpr=2.6.9=py36h637b7d7_1000
  - olefile=0.46=py_0
  - openssl=1.0.2p=h14c3975_1002
  - packaging=19.0=py_0
  - pandas=0.23.4=py36h637b7d7_1000
  - pandoc=2.5=1
  - pandocfilters=1.4.2=py_1
  - parso=0.3.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pillow=5.4.1=py36h00a061d_1000
  - pip=18.1=py36_1000
  - plac=0.9.6=py_1
  - prometheus_client=0.5.0=py_0
  - prompt_toolkit=2.0.7=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py36_1000
  - pycparser=2.19=py_0
  - pygments=2.3.1=py_0
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.3.1=py_0
  - pyqt=5.6.0=py36h13b7fb3_1008
  - pyrsistent=0.14.9=py36h14c3975_1000
  - pysocks=1.6.8=py36_1002
  - python=3.6.7=hd21baee_1001
  - python-dateutil=2.7.5=py_0
  - pytz=2018.9=py_0
  - pyyaml=3.13=py36h14c3975_1001
  - pyzmq=17.1.2=py36h6afc9c9_1001
  - qt=5.6.2=hf70d934_9
  - qtconsole=4.4.3=py_0
  - readline=7.0=hf8c457e_1001
  - regex=2018.01.10=py36h14c3975_1000
  - requests=2.21.0=py36_1000
  - send2trash=1.5.0=py_0
  - setuptools=40.6.3=py36_0
  - sip=4.18.1=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - soupsieve=1.7.1=py36_1000
  - spacy=2.0.18=py36hf484d3e_1000
  - sqlite=3.26.0=h67949de_1000
  - terminado=0.8.1=py36_1001
  - testpath=0.4.2=py36_1000
  - thinc=6.12.1=py36h637b7d7_1000
  - tk=8.6.9=h84994c4_1000
  - toolz=0.9.0=py_1
  - torchvision=0.2.1=py36_1000
  - tornado=5.1.1=py36h14c3975_1000
  - tqdm=4.29.1=py_0
  - traitlets=4.3.2=py36_1000
  - typing=3.6.4=py36_0
  - ujson=1.35=py36h14c3975_1001
  - urllib3=1.24.1=py36_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.32.3=py36_0
  - widgetsnbextension=3.4.2=py36_1000
  - wrapt=1.10.11=py36h14c3975_1001
  - xorg-libxau=1.0.8=h14c3975_1006
  - xorg-libxdmcp=1.1.2=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.2.5=hf484d3e_1006
  - zlib=1.2.11=h14c3975_1004
  - zstd=1.3.3=1
  - blas=1.0=mkl
  - cymem=2.0.2=py36hfd86e86_0
  - intel-openmp=2019.1=144
  - mkl=2019.1=144
  - numpy=1.15.4=py36h7e9f1db_0
  - numpy-base=1.15.4=py36hde5b4d6_0
  - preshed=2.0.1=py36he6710b0_0
  - scipy=1.2.0=py36h7c811a0_0
  - fastai=1.0.42=1
  - fastprogress=0.1.18=py_0
  - nvidia-ml-py3=7.352.0=py_0
  - cuda92=1.0=0
  - pytorch=1.0.0=py3.6_cuda9.0.176_cudnn7.4.1_1
  - pip:
    - boto==2.49.0
    - boto3==1.11.0
    - botocore==1.14.0
    - dataclasses==0.6
    - docutils==0.15.2
    - gensim==3.8.1
    - jmespath==0.9.4
    - joblib==0.14.1
    - msgpack==0.5.6
    - nltk==3.4.5
    - s3transfer==0.3.0
    - scikit-learn==0.22.1
    - smart-open==1.9.0
    - torch==1.0.0
prefix: /opt/conda/envs/fastai

